import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#f9f9f9',
  },
  menuButton: {
    position: 'absolute',
    top: 20,
    left: 10,
    zIndex: 2,
  },
  drawer: {
    position: 'absolute',
    left: 0,
    top: 0,
    width: 200,
    height: '100%',
    backgroundColor: '#ffffff',
    borderRightWidth: 1,
    borderRightColor: '#ddd',
    justifyContent: 'flex-start',
    paddingTop: 40,
    zIndex: 3,
  },
  perfilBox: {
    backgroundColor: '#ffffff',
    paddingVertical: 30,
    paddingHorizontal: 25,
    width: 380,
    borderRadius: 16,
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    marginTop: 40,
    marginBottom: 20,
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#222222',
    marginBottom: 20,
    textAlign: 'center',
  },
  infoRow: {
    marginBottom: 20,
  },
  label: {
    fontWeight: '600',
    fontSize: 16,
    color: '#000000',
    marginBottom: 6,
  },
  input: {
    backgroundColor: '#ffffff',
    textShadowColor: '#000000',
    color: '#000000',
  },
  button: {
    backgroundColor: '#000000',
    borderRadius: 8,
    marginTop: 20,
    width: '100%',
  },
  buttonText: {
    color: '#f4f6f6',
    fontSize: 16,
    textAlign: 'center',
  },
  drawerContainer: {
    backgroundColor: '#fff',
    padding: 20,
    width: 250,
    alignSelf: 'flex-start',
    borderRadius: 10,
    minHeight: 300,
  },
});
